##------------------------------------------------------------------------
##-Each new term in the Fibonacci sequence is generated by adding
##-the previous two terms. By starting with 1 and 2, the first 10
##-terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...-
##-By considering the terms in the Fibonacci sequence whose
##-values do not exceed four million, find the sum of the even-valued terms.
##------------------------------------------------------------------------
##-jim mccleery, november, 2021, modified March, 2023
##------------------------------------------------------------------------
def fib_gen():
    fa = 1
    yield fa
    fb = 2
    yield fb
    while True:
        yield fa+fb
        fa,fb = fb,fa+fb
##------------------------------------------------------------------------        
fg = fib_gen()
total = 0
while True:
    fib = next(fg)
    if fib > 4*10**6:
        break
    if fib % 2 == 0:
        total += fib
print(total)
##------------------------------------------------------------------------
## solution: 4613732
##------------------------------------------------------------------------
