################################################################################
# 44-pentagonal.py
#
# Pentagonal numbers are generated by the formula, Pn =  n(3n−1)/2.
# The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
# However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum
# and difference are pentagonal and D = |Pk − Pj| is minimised;
# what is the value of D?
################################################################################
import itertools
################################################################################
def getTheCombos(pentList):
    combos = itertools.combinations(pentList,2)
    comboLst = list(combos)
    return(comboLst)
################################################################################        
def makePentList(start,stop):
    pentList = []
    for i in range(start,stop+1):
        pentList.append((i * (3*i-1)) // 2)
    return(pentList)
################################################################################
START = 1_000
STOP = 3_000
minPinDiff = 1_000_000_000
pin01 = 1
pin02 = 5

thePentList = makePentList(START,STOP)
theComboList = getTheCombos(thePentList)
for i in range(len(theComboList)):
    currentCombo = theComboList[i]
    sum = currentCombo[0] + currentCombo[1]
    dif = abs(currentCombo[0] - currentCombo[1])
    if sum in thePentList and dif in thePentList:
        if minPinDiff > dif:
            minPinDiff = dif
            pin01 = currentCombo[0]
            pin02 = currentCombo[1]

if pin01 != 1:
    print('Pentagonal01:',pin01,'Pentagonal02:',pin02,'Difference:',minPinDiff)
else:
    print('No solution found.')
        
################################################################################
#solution: 5482660
################################################################################
    
