################################################################################
##Cyclical figurate numbers
##Problem 61
##Triangle, square, pentagonal, hexagonal, heptagonal,
##and octagonal numbers are all figurate (polygonal) numbers
##and are generated by the following formulae:
##
##Triangle	P3,n=n(n+1)/2	1, 3, 6, 10, 15, ...
##Square	 	P4,n=n^2	 	1, 4, 9, 16, 25, ...
##Pentagonal	P5,n=n(3n−1)/2	1, 5, 12, 22, 35, ...
##Hexagonal	P6,n=n(2n−1)	1, 6, 15, 28, 45, ...
##Heptagonal	P7,n=n(5n−3)/2	1, 7, 18, 34, 55, ...
##Octagonal	P8,n=n(3n−2)	1, 8, 21, 40, 65, ...
##
##The ordered set of three 4-digit numbers: 8128, 2882, 8281,
##has three interesting properties.
##
##The set is cyclic, in that the last two digits of each number
##is the first two digits of the next number (including the last
##number with the first).
##
##Each polygonal type: triangle (P3,127=8128), square (P4,91=8281),
##and pentagonal (P5,44=2882), is represented by a different number in the set.
##This is the only set of 4-digit numbers with this property.
##Find the sum of the only ordered set of six cyclic 4-digit
##numbers for which each polygonal type: triangle, square, pentagonal,
##hexagonal, heptagonal, and octagonal, is represented by a different
##number in the set.
################################################################################
import numpy as np
################################################################################
#number lists
triList = []
squList = []
penList = []
hexList = []
hepList = []
octList = []
theSolution = []
listArray = np.zeros((96,7),int)
################################################################################
def loadArray():
    for row in range(96):
        for col in range(7):
            if col == 0:
                listArray[row,col] = octList[row]
            elif col == 1:
                listArray[row,col] = hexList[row]
            elif col == 2:
                listArray[row,col] = penList[row]
            elif col == 3:
                listArray[row,col] = triList[row]
            elif col == 4:
                listArray[row,col] = squList[row]
            elif col == 5:
                listArray[row,col] = hepList[row]
            else:
                listArray[row,col] = octList[row]  
################################################################################
def findIndex(right2,solList):
    for i in range(len(solList)):
        left2 = solList[i] // 100
        if right2 == left2:
            return(i)
################################################################################
def organizeSolList(solList):
    newList = []
    firstValue = min(solList)
    newList.append(firstValue)
    while len(newList) != 6:
        right2 = newList[len(newList)-1] % 100
        index = findIndex(right2,solList)
        newList.append(solList[index])
    return(newList)
################################################################################
def solution():
    solList = []
    for col in range(6):
        for row in range(96):
            if listArray[row,col] != 0:
                solList.append(listArray[row,col])
    return organizeSolList(solList)
################################################################################
def knockOut():
    right2 = set()
    for col in range(6):
        right2.clear()
        for row in range(96):
            right2.add(listArray[row,col] % 100)
        for row in range(96):
            left2 = listArray[row,col+1] // 100
            if left2 not in right2:
                listArray[row,col+1] = 0       
################################################################################
def countNonZeros():
    counter = 0
    for row in range(96):
        for col in range(6):
            if listArray[row][col] != 0:
                counter += 1
    return counter
################################################################################    
def swapCols(c1,c2):
    for row in range(96):
        temp = listArray[row,c1]
        listArray[row,c1] = listArray[row,c2]
        listArray[row,c2] = temp
        if c1 == 0 or c2 == 0:
            listArray[row,6] = listArray[row,0]
################################################################################
def makeTri(n):
    return n*(n+1)//2
################################################################################
def makeTriList():
    counter = 1
    while True:
        tri = makeTri(counter)
        if tri > 999 and tri <= 9999:
            triList.append(tri)
        elif tri > 9999:
            return
        counter += 1
################################################################################
def makeSqu(n):
    return n**2
################################################################################
def makeSquList():
    counter = 1
    while True:
        squ = makeSqu(counter)
        if squ > 999 and squ <= 9999:
            squList.append(squ)
        elif squ > 9999:
            break
        counter += 1
    while len(squList) < 96:
        squList.append(0)
################################################################################
def makePen(n):
    return n*(3*n-1)//2
################################################################################
def makePenList():
    counter = 1
    while True:
        pen = makePen(counter)
        if pen > 999 and pen <= 9999:
            penList.append(pen)
        elif pen > 9999:
            break
        counter += 1
    while len(penList) < 96:
        penList.append(0)
################################################################################
def makeHex(n):
    return n*(2*n-1)
################################################################################
def makeHexList():
    counter = 1
    while True:
        hex = makeHex(counter)
        if hex > 999 and hex <= 9999:
            hexList.append(hex)
        elif hex > 9999:
            break
        counter += 1
    while len(hexList) < 96:
        hexList.append(0)
################################################################################
def makeHep(n):
    return n*(5*n-3)//2
################################################################################
def makeHepList():
    counter = 1
    while True:
        hep = makeHep(counter)
        if hep > 999 and hep <= 9999:
            hepList.append(hep)
        elif hep > 9999:
            break
        counter += 1
    while len(hepList) < 96:
        hepList.append(0)
################################################################################
def makeOct(n):
    return n*(3*n-2)
################################################################################
def makeOctList():
    counter = 1
    while True:
        oct = makeOct(counter)
        if oct > 999 and oct <= 9999:
            octList.append(oct)
        elif oct > 9999:
            break
        counter += 1
    while len(octList) < 96:
        octList.append(0)
################################################################################
def makeLists():
    makeTriList()
    makeSquList()
    makePenList()
    makeHexList()
    makeHepList()
    makeOctList()
################################################################################
makeLists()
loadArray()
while countNonZeros() != 6:
    knockOut()
    swapCols(6,0)
theSolution = solution()
print('Solution List:',theSolution,'Solution Sum:',sum(theSolution))
################################################################################
#solution: 28684,   [1281, 8128, 2882, 8256, 5625, 2512]
#                   [oct,  hex,  pen,  tri,  squ,  hep]     
################################################################################
