"""
Jim McCleery
April 4, 2026
Kailua-Kona, HI

Credit to zeycus on Project Euler

Overview
--------
This program studies pairs of integers of the form

    (numerator, denominator)

that are generated by a recurrence process.

For each positive integer n, we begin with a standard starting pair.
From that starting pair, we generate additional related pairs by following
one or two possible "child" rules. In this way, the program explores a
tree of states.

The goal is to collect certain special numbers called pivots and then
compute the sum of all distinct pivots up to a specified bound.

High-level strategy
-------------------
1. Generate all starting states whose denominators do not exceed the bound.
2. Store those states in a list called 'pending'.
3. Repeatedly remove one state from 'pending'.
4. Compute its pivot, if it has one.
5. Generate its children and add them to 'pending' if they remain within bounds.
6. Use a set to keep only distinct pivots.

Computer science note
---------------------
Because we use

    pending.append(...)
    pending.pop()

on the same end of the list, 'pending' behaves like a stack.

A stack is "last in, first out" (LIFO), meaning the most recently added
state is the next one processed. That gives a depth-first search (DFS):
the program tends to follow one branch deeply before backing up and
exploring another branch.
"""

from itertools import count


def get_rule_coefficients(n):
    """
    Return the six coefficients used in the recurrence rule.

    For a current solution pair (numerator, denominator), the next pair is:

        new_numerator   = a1*numerator + a2*denominator + a3
        new_denominator = b1*numerator + b2*denominator + b3

    The coefficients depend on n.
    """
    a1 = 2 * n + 1
    a2 = 2 * n + 2
    a3 = 2 * n**2

    b1 = 2 * n
    b2 = 2 * n + 1
    b3 = 2 * n**2 - n

    return a1, a2, a3, b1, b2, b3


def get_standard_solution(n):
    """
    Return the standard starting solution for a given n.

    This is the initial (numerator, denominator) pair from which all
    other pairs associated with this n are generated.
    """
    numerator = 2 * n * (n + 1) + 1
    denominator = n * (2 * n + 1)
    return numerator, denominator


def next_solution(solution, n):
    """
    Apply one step of the recurrence rule for the given n.

    Parameters
    ----------
    solution : tuple[int, int]
        A pair (numerator, denominator).
    n : int
        The parameter that determines the recurrence coefficients.

    Returns
    -------
    tuple[int, int]
        The next solution pair produced by the rule.
    """
    numerator, denominator = solution

    a1, a2, a3, b1, b2, b3 = get_rule_coefficients(n)

    new_numerator = a1 * numerator + a2 * denominator + a3
    new_denominator = b1 * numerator + b2 * denominator + b3

    return new_numerator, new_denominator


def children(solution, n):
    """
    Generate the children of the current state.

    A state consists of:
        (solution, n)

    where solution = (numerator, denominator).

    There are at most two children:

    1. The next solution produced by the recurrence rule for the same n.
    2. A second branch obtained by changing the state when

           numerator - denominator - 1 > n

    Yields
    ------
    tuple[tuple[int, int], int]
        A child state of the form ((numerator, denominator), n_value).
    """
    numerator, denominator = solution

    # Child 1: continue the recurrence using the same n.
    yield next_solution(solution, n), n

    # Child 2: branch to a different state if the condition is satisfied.
    if numerator - denominator - 1 > n:
        yield (denominator + n + 1, denominator), numerator - denominator - 1


def compute_pivot(solution, n, bound):
    """
    Compute the pivot value for a state.

    The candidate pivot is

        denominator + n

    but it is only accepted if both of the following conditions hold:

        numerator > denominator + n
        denominator + n <= bound

    If the candidate is valid, return it.
    Otherwise return None.

    Returning None is clearer than returning 0, because it shows that
    no pivot exists for this state.
    """
    numerator, denominator = solution
    candidate = denominator + n

    if numerator > candidate and candidate <= bound:
        return candidate

    return None


def main():
    """
    Run the full search and print the sum of all distinct pivots.

    The list 'pending' is used as a stack.

    Why does this produce depth-first search?
    -----------------------------------------
    Suppose a state produces a child. That child is appended to the end
    of the list. Later, when we call pop(), we remove from that same end.
    Therefore the newest child is processed next.

    In other words:
        append -> put new work on top of the stack
        pop    -> take work from the top of the stack

    This "last in, first out" behavior makes the program follow one path
    downward as far as it can before returning to older branches.
    """
    bound = 10**10
    pending = []

    # Step 1: Build the initial list of starting states.
    for n in count(1):
        start_solution = get_standard_solution(n)

        # Once the denominator exceeds the bound, we can stop.
        if start_solution[1] > bound:
            break

        pending.append((start_solution, n))

    pivots = set()

    # Step 2: Explore all reachable states.
    while pending:
        solution, n = pending.pop()

        pivot_value = compute_pivot(solution, n, bound)
        if pivot_value is not None:
            pivots.add(pivot_value)

        for child_solution, child_n in children(solution, n):
            if child_solution[1] <= bound:
                pending.append((child_solution, child_n))

    # Step 3: Print the sum of all distinct pivots.
    print("Solution:", sum(pivots))


if __name__ == "__main__":
    main()
