#  -----------------------------------------------------------------------------
#  An enormous factorial
#  Problem 288
#  For any prime p the number N(p,q) is defined by N(p,q) = ∑n=0 to q Tn*pn
#  with Tn generated by the following random number generator:
#  
#  S0 = 290797
#  Sn+1 = Sn^2 mod 50515093
#  Tn = Sn mod p
#  
#  Let Nfac(p,q) be the factorial of N(p,q).
#  Let NF(p,q) be the number of factors p in Nfac(p,q).
#  
#  You are given that NF(3,10000) mod 3^20 = 624955285.
#  
#  Find NF(61,10^7) mod 61^10
#  -----------------------------------------------------------------------------
def NFmod(p, q, e):
    m = p ** e
    s = 290797
    r = 0
    x = 0
    for n in range(q + 1):
        t = s % p
        s = s * s % 50515093
        r = (r + t * x) % m
        if n < e:
            x += p ** n
    return r % m
#  -----------------------------------------------------------------------------
print(NFmod(3,10**4,20))
print(NFmod(61,10**7,10))
#  -----------------------------------------------------------------------------
#  solution: 605857431263981935
#  -----------------------------------------------------------------------------
